name: appname
description: "Ecommerce Admin Dashboard with Flutter"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  glassmorphism: ^3.0.0
  supabase_flutter: ^2.9.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter: 
  uses-material-design: true
